#!/bin/bash
# 특정 서비스를  실행하면 restart-enable-status 순서로 실행
# new start sshd
# -> systemctl restart sshd
# -> systemctl enable sshd
# -> systemctl status sshd

# 특정 서비스를 종료하면 stop-disable-status 순서로 실행
# new stop sshd
# -> systemctl stop sshd
# -> systemctl disable sshd
# -> systemctl status sshd

if [ $# -ne 2 ]; then
    echo "Usage: $0 <start|stop> UNIT"
    exit 1
fi
ACTION=$1
UNIT=$2

case $ACTION in
    start) systemctl restart $UNIT  \
            && systemctl enable $UNIT \
            && systemctl status $UNIT ;;
    stop ) systemctl stop $UNIT \
            && systemctl disable $UNIT \
            && systemctl status $UNIT ;;
    *    ) echo "Usage $0 <stop|stop> UNIT"
           exit 1 ;; 
esac




